#### GET all meals
GET http://localhost:8080/topjava/rest/meals
Accept: application/json

#### GET by id
GET http://localhost:8080/topjava/rest/meals/100004
Accept: application/json

#### DELETE by id
DELETE http://localhost:8080/topjava/rest/meals/100004
Accept: application/json

#### POST create by id
POST http://localhost:8080/topjava/rest/meals
Content-Type: application/json

{
    "dateTime": "2020-01-31T14:00:00",
    "description": "Обед2",
    "calories": 751
}

#### PUT update by id
PUT http://localhost:8080/topjava/rest/meals/100007
Content-Type: application/json

{
    "dateTime": "2020-01-31T10:00",
    "description": "Завтрак",
    "calories": 55
}

### GET with a filter
GET http://localhost:8080/topjava/rest/meals/filter?startDate=2020-01-30&startTime=10:30&endDate=2020-01-31&endTime=17:30
Accept: application/json

### GET with a filter nulls values
GET http://localhost:8080/topjava/rest/meals/filter?startDate=2020-01-30&startTime=10:30
Accept: application/json

